/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    CompletedTopicCard: typeof import('./src/components/CompletedTopicCard.vue')['default']
    CompletedTopics: typeof import('./src/components/CompletedTopics.vue')['default']
    CurrentTopic: typeof import('./src/components/CurrentTopic.vue')['default']
    CurrentTopicProgressBar: typeof import('./src/components/CurrentTopicProgressBar.vue')['default']
    IconMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IconMdiNotebookOutline: typeof import('~icons/mdi/notebook-outline')['default']
    IconMdiRestart: typeof import('~icons/mdi/restart')['default']
    IconMdiRestartAlert: typeof import('~icons/mdi/restart-alert')['default']
    TheIntroduction: typeof import('./src/components/TheIntroduction.vue')['default']
    UploadTopics: typeof import('./src/components/UploadTopics.vue')['default']
  }
}
